Fixup changelog that causes errors.
This fixes the following Debian git-build-recipe error:

RUN ['git-build-recipe', '--safe', '--no-build', '--manifest', '/home/buildd/build-RECIPEBRANCHBUILD-1302092/chroot-autobuild/home/buildd/work/tree/manifest', '--distribution', 'xenial', '--allow-fallback-to-native', '--append-version', '~ubuntu16.04.1', '/home/buildd/build-RECIPEBRANCHBUILD-1302092/chroot-autobuild/home/buildd/work/recipe', '/home/buildd/build-RECIPEBRANCHBUILD-1302092/chroot-autobuild/home/buildd/work/tree']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/deb_util.py", line 139, in add_autobuild_changelog_entry
    substitute_changelog_vars(base_branch, None, cl)
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/deb_version.py", line 172, in substitute_changelog_vars
    base_branch.deb_version = debupstream_var.replace(base_branch.deb_version)
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/recipe.py", line 101, in replace
    return value.replace(self.name, self.get())
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/deb_version.py", line 59, in get
    "No previous changelog to take the upstream version from")
gitbuildrecipe.recipe.SubstitutionUnavailable: Substitution for {debupstream} not available: No previous changelog to take the upstream version from

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/git-build-recipe", line 9, in <module>
    load_entry_point('git-build-recipe==0.1', 'console_scripts', 'git-build-recipe')()
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/main.py", line 147, in main
    append_version=args.append_version)
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/deb_util.py", line 143, in add_autobuild_changelog_entry
    "%s was used: %s: %s." % (e.name, e.reason, reason))
Exception: No previous changelog to take the upstream version from as {debupstream} was used: No previous changelog to take the upstream version from: debian/changelog didn't contain any parseable stanzas.
resource.struct_rusage(ru_utime=1.7839999999999998, ru_stime=1.116, ru_maxrss=33232, ru_ixrss=0, ru_idrss=0, ru_isrss=0, ru_minflt=25805, ru_majflt=41, ru_nswap=0, ru_inblock=12560, ru_oublock=18536, ru_msgsnd=0, ru_msgrcv=0, ru_nsignals=0, ru_nvcsw=1382, ru_nivcsw=290)
RUN: /usr/share/launchpad-buildd/slavebin/scan-for-processes ['scan-for-processes', 'RECIPEBRANCHBUILD-1302092']
Scanning for processes to kill in build /home/buildd/build-RECIPEBRANCHBUILD-1302092/chroot-autobuild...
RUN: /usr/share/launchpad-buildd/slavebin/umount-chroot ['umount-chroot', 'RECIPEBRANCHBUILD-1302092']
Unmounting chroot for build RECIPEBRANCHBUILD-1302092...
RUN: /usr/share/launchpad-buildd/slavebin/remove-build ['remove-build', 'RECIPEBRANCHBUILD-1302092']
Removing build RECIPEBRANCHBUILD-1302092

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>